# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-21 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polling', '0001_initial_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='polloption',
            name='final',
            field=models.BooleanField(default=False),
        ),
    ]
