# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-29 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Polling', '0002_polloption_final'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyPollOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final', models.BooleanField(default=False)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(5, 'شنبه'), (6, 'یکشنبه'), (0, 'دوشنبه'), (1, 'سه شنبه'), (2, 'چهارشنبه'), (3, 'پنجشنبه'), (4, 'جمعه')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polling.Poll')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='PollOption',
            new_name='NormalPollOption',
        ),
    ]
