# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-02 12:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Polling', '0005_poll_is_normal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1024)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.RenameField(
            model_name='userpoll',
            old_name='choices',
            new_name='choice',
        ),
        migrations.AddField(
            model_name='comment',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Polling.UserPoll'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polling.Comment'),
        ),
    ]
